(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [solana_sbpf] *)

theory SbpfSafeEncode
  imports
    "Primitives"
begin


(* Trait declaration: [core::cmp::PartialEq]
   Source: '/rustc/library/core/src/cmp.rs', lines 250:0-250:65
   Name pattern: [core::cmp::PartialEq]
   Visibility: public *)
record ('self, 'rhs) core_cmp_PartialEq_t =
  core_cmp_PartialEq_t_eq :: " 'self ⇒ 'rhs ⇒ bool result"

(* [core::cmp::Ordering]
   Source: '/rustc/library/core/src/cmp.rs', lines 405:0-405:17
   Name pattern: [core::cmp::Ordering]
   Visibility: public *)
datatype core_cmp_Ordering_t =
    Core_cmp_Ordering_Less
  | Core_cmp_Ordering_Equal
  | Core_cmp_Ordering_Greater

(* Trait declaration: [core::cmp::PartialOrd]
   Source: '/rustc/library/core/src/cmp.rs', lines 1366:0-1367:41
   Name pattern: [core::cmp::PartialOrd]
   Visibility: public *)
record ('self, 'rhs) core_cmp_PartialOrd_t =
  core_cmp_PartialOrd_tcore_cmp_PartialOrd_t_PartialEqInst :: " ('self, 'rhs)
    core_cmp_PartialEq_t"
  core_cmp_PartialOrd_t_partial_cmp :: " 'self ⇒ 'rhs ⇒
    (core_cmp_Ordering_t option) result"

(* [core::cmp::impls::{impl core::cmp::PartialEq<i32> for i32}::eq]:
   Source: '/rustc/library/core/src/cmp.rs', lines 1878:16-1878:50
   Name pattern: [core::cmp::impls::{core::cmp::PartialEq<i32, i32>}::eq]
   Visibility: public *)
axiomatization i32_Insts_CoreCmpPartialEqI32_eq ::
  "i32 ⇒ i32 ⇒ bool result"

(* [core::cmp::impls::{impl core::cmp::PartialOrd<i32> for i32}::partial_cmp]:
   Source: '/rustc/library/core/src/cmp.rs', lines 1999:16-1999:71
   Name pattern: [core::cmp::impls::{core::cmp::PartialOrd<i32, i32>}::partial_cmp]
   Visibility: public *)
axiomatization i32_Insts_CoreCmpPartialOrdI32_partial_cmp ::
  "i32 ⇒ i32 ⇒ (core_cmp_Ordering_t option) result"

(* [core::fmt::Arguments]
   Source: '/rustc/library/core/src/fmt/mod.rs', lines 716:0-716:24
   Name pattern: [core::fmt::Arguments] *)
typedecl core_fmt_Arguments_t

(* [core::ops::range::RangeInclusive]
   Source: '/rustc/library/core/src/ops/range.rs', lines 357:0-357:30
   Name pattern: [core::ops::range::RangeInclusive] *)
typedecl 'idx core_ops_range_RangeInclusive_t

(* [core::ops::range::{core::ops::range::RangeInclusive<Idx>}::new]:
   Source: '/rustc/library/core/src/ops/range.rs', lines 390:4-390:50
   Name pattern: [core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::new]
   Visibility: public *)
axiomatization core_ops_range_RangeInclusive_new ::
  "'idx ⇒ 'idx ⇒ ('idx core_ops_range_RangeInclusive_t) result"

(* [core::ops::range::{core::ops::range::RangeInclusive<Idx>}::contains]:
   Source: '/rustc/library/core/src/ops/range.rs', lines 522:4-525:44
   Name pattern: [core::ops::range::{core::ops::range::RangeInclusive<@Idx>}::contains]
   Visibility: public *)
axiomatization core_ops_range_RangeInclusive_contains ::
  "('idx, 'idx) core_cmp_PartialOrd_t ⇒ ('idx, 'u) core_cmp_PartialOrd_t ⇒
    ('u, 'idx) core_cmp_PartialOrd_t ⇒ ('idx core_ops_range_RangeInclusive_t)
    ⇒ 'u ⇒ bool result"

(* [core::panicking::AssertKind]
   Source: '/rustc/library/core/src/panicking.rs', lines 373:0-373:19
   Name pattern: [core::panicking::AssertKind]
   Visibility: public *)
datatype core_panicking_AssertKind_t =
    Core_panicking_AssertKind_Eq
  | Core_panicking_AssertKind_Ne
  | Core_panicking_AssertKind_Match

(* Trait implementation: [core::slice::index::private_slice_index::{impl core::slice::index::private_slice_index::Sealed for core::ops::range::RangeTo<usize>}]
   Source: '/rustc/library/core/src/slice/index.rs', lines 116:4-116:39
   Name pattern: [core::slice::index::private_slice_index::Sealed<core::ops::range::RangeTo<usize>>] *)
definition
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexPrivate_slice_indexSealed ::
  "(usize core_ops_range_RangeTo) core_slice_index_private_slice_index_Sealed"
  where
  "core_ops_range_RangeToUsize_Insts_CoreSliceIndexPrivate_slice_indexSealed = (| core_slice_index_private_slice_index_Sealed_dummy = () |)"

(* [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::index_mut]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 533:4-533:51
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::index_mut]
   Visibility: public *)
axiomatization
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index_mut
  ::
  "(usize core_ops_range_RangeTo) ⇒ ('t slice) ⇒ (('t slice) × ('t slice
    ⇒ 't slice)) result"

(* [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::index]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 528:4-528:39
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::index]
   Visibility: public *)
axiomatization
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index ::
  "(usize core_ops_range_RangeTo) ⇒ ('t slice) ⇒ ('t slice) result"

(* [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::get_unchecked_mut]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 522:4-522:66
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::get_unchecked_mut]
   Visibility: public *)
axiomatization
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked_mut
  ::
  "(usize core_ops_range_RangeTo) ⇒ (('t slice) mut_raw_ptr) ⇒ (('t slice)
    mut_raw_ptr) result"

(* [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::get_unchecked]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 516:4-516:66
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::get_unchecked]
   Visibility: public *)
axiomatization
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked
  ::
  "(usize core_ops_range_RangeTo) ⇒ (('t slice) const_raw_ptr) ⇒ (('t
    slice) const_raw_ptr) result"

(* [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::get_mut]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 511:4-511:57
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::get_mut]
   Visibility: public *)
axiomatization
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_mut
  ::
  "(usize core_ops_range_RangeTo) ⇒ ('t slice) ⇒ ((('t slice) option) ×
    (('t slice) option ⇒ 't slice)) result"

(* [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}::get]:
   Source: '/rustc/library/core/src/slice/index.rs', lines 506:4-506:45
   Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>}::get]
   Visibility: public *)
axiomatization
  core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get ::
  "(usize core_ops_range_RangeTo) ⇒ ('t slice) ⇒ (('t slice) option)
    result"

(* Trait implementation: [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeTo<usize>}]
   Source: '/rustc/library/core/src/slice/index.rs', lines 502:0-502:60
   Name pattern: [core::slice::index::SliceIndex<core::ops::range::RangeTo<usize>, [@T], [@T]>] *)
definition core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
  :: "((usize core_ops_range_RangeTo), ('t slice), ('t slice))
  core_slice_index_SliceIndex" where
  "core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice = (|
  sealedInst =
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexPrivate_slice_indexSealed,
  
  core_slice_index_SliceIndex_get =
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get,
  
  core_slice_index_SliceIndex_get_mut =
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_mut,
  
  core_slice_index_SliceIndex_get_unchecked =
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked,
  
  core_slice_index_SliceIndex_get_unchecked_mut =
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked_mut,
  
  core_slice_index_SliceIndex_index =
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index,
  
  core_slice_index_SliceIndex_index_mut =
    core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index_mut
|)"

(* [alloc::vec::{alloc::vec::Vec<T>}::extend_from_slice]:
   Source: '/rustc/library/alloc/src/vec/mod.rs', lines 3563:4-3563:52
   Name pattern: [alloc::vec::{alloc::vec::Vec<@T>}::extend_from_slice]
   Visibility: public *)
axiomatization alloc_vec_Vec_extend_from_slice ::
  "'t core_clone_Clone ⇒ ('t alloc_vec_Vec) ⇒ ('t slice) ⇒ ('t
    alloc_vec_Vec) result"

(* [solana_sbpf::safe_mode::jit::OperandSize]
   Source: 'src/safe_mode/jit.rs', lines 12:0-23:1
   Visibility: public *)
datatype safe_mode_jit_OperandSize_t =
    Safe_mode_jit_OperandSize_S0
  | Safe_mode_jit_OperandSize_S8
  | Safe_mode_jit_OperandSize_S16
  | Safe_mode_jit_OperandSize_S32
  | Safe_mode_jit_OperandSize_S64

(* [solana_sbpf::safe_mode::x86::X86Register]
   Source: 'src/safe_mode/x86.rs', lines 23:0-48:1
   Visibility: public *)
datatype safe_mode_x86_X86Register_t =
    Safe_mode_x86_X86Register_RAX
  | Safe_mode_x86_X86Register_RCX
  | Safe_mode_x86_X86Register_RDX
  | Safe_mode_x86_X86Register_RBX
  | Safe_mode_x86_X86Register_RSP
  | Safe_mode_x86_X86Register_RBP
  | Safe_mode_x86_X86Register_RSI
  | Safe_mode_x86_X86Register_RDI
  | Safe_mode_x86_X86Register_R8
  | Safe_mode_x86_X86Register_R9
  | Safe_mode_x86_X86Register_R10
  | Safe_mode_x86_X86Register_R11
  | Safe_mode_x86_X86Register_R12
  | Safe_mode_x86_X86Register_R13
  | Safe_mode_x86_X86Register_R14
  | Safe_mode_x86_X86Register_R15
  | Safe_mode_x86_X86Register_MM0
  | Safe_mode_x86_X86Register_MM1
  | Safe_mode_x86_X86Register_MM2
  | Safe_mode_x86_X86Register_MM3
  | Safe_mode_x86_X86Register_MM4
  | Safe_mode_x86_X86Register_MM5
  | Safe_mode_x86_X86Register_MM6
  | Safe_mode_x86_X86Register_MM7

(* [solana_sbpf::safe_mode::x86::X86Rex]
   Source: 'src/safe_mode/x86.rs', lines 55:0-60:1 *)
record safe_mode_x86_X86Rex_t =
  Safe_mode_x86_X86Rex_w :: "bool"
  Safe_mode_x86_X86Rex_r :: "bool"
  Safe_mode_x86_X86Rex_x :: "bool"
  Safe_mode_x86_X86Rex_b :: "bool"

(* [solana_sbpf::safe_mode::x86::X86ModRm]
   Source: 'src/safe_mode/x86.rs', lines 62:0-66:1 *)
record safe_mode_x86_X86ModRm_t =
  Safe_mode_x86_X86ModRm_mode :: "u8"
  Safe_mode_x86_X86ModRm_r :: "u8"
  Safe_mode_x86_X86ModRm_m :: "u8"

(* [solana_sbpf::safe_mode::x86::X86Sib]
   Source: 'src/safe_mode/x86.rs', lines 68:0-72:1 *)
record safe_mode_x86_X86Sib_t =
  Safe_mode_x86_X86Sib_scale :: "u8"
  Safe_mode_x86_X86Sib_index :: "u8"
  Safe_mode_x86_X86Sib_base :: "u8"

(* [solana_sbpf::safe_mode::x86::X86IndirectAccess]
   Source: 'src/safe_mode/x86.rs', lines 75:0-80:1
   Visibility: public *)
datatype safe_mode_x86_X86IndirectAccess_t =
    Safe_mode_x86_X86IndirectAccess_Offset "i32"
  | Safe_mode_x86_X86IndirectAccess_OffsetIndexShift
      "i32"
      "safe_mode_x86_X86Register_t"
      "u8"

(* [solana_sbpf::safe_mode::x86::X86Instruction]
   Source: 'src/safe_mode/x86.rs', lines 91:0-101:1
   Visibility: public *)
record safe_mode_x86_X86Instruction_t =
  Safe_mode_x86_X86Instruction_size :: "safe_mode_jit_OperandSize_t"
  Safe_mode_x86_X86Instruction_opcode_escape_sequence :: "u8"
  Safe_mode_x86_X86Instruction_opcode :: "u8"
  Safe_mode_x86_X86Instruction_modrm :: "bool"
  Safe_mode_x86_X86Instruction_indirect :: "safe_mode_x86_X86IndirectAccess_t
    option"
  Safe_mode_x86_X86Instruction_first_operand :: "u8"
  Safe_mode_x86_X86Instruction_second_operand :: "u8"
  Safe_mode_x86_X86Instruction_immediate_size :: "safe_mode_jit_OperandSize_t"
  Safe_mode_x86_X86Instruction_immediate :: "i64"

(* [solana_sbpf::safe_mode::x86::emit_variable_length]:
   Source: 'src/safe_mode/x86.rs', lines 784:0-793:1 *)
definition safe_mode_x86_emit_variable_length
  :: "(u8 alloc_vec_Vec) ⇒ safe_mode_jit_OperandSize_t ⇒ u64 ⇒ (u8
  alloc_vec_Vec) result"
  where
  "safe_mode_x86_emit_variable_length output size' data
    = (
    let bytes = core_num_U64_to_le_bytes data in
    case size' of
    Safe_mode_jit_OperandSize_S0 => (Ok output)
    | Safe_mode_jit_OperandSize_S8 =>
      ((s <-
          core_array_Array_index (8 :: usize) (core_ops_index_IndexSliceInst
            core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice)
            bytes (| core_ops_range_RangeTo_end_' = (1 :: usize) |);
       alloc_vec_Vec_extend_from_slice core_clone_CloneU8 output s))
    | Safe_mode_jit_OperandSize_S16 =>
      ((s <-
          core_array_Array_index (8 :: usize) (core_ops_index_IndexSliceInst
            core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice)
            bytes (| core_ops_range_RangeTo_end_' = (2 :: usize) |);
       alloc_vec_Vec_extend_from_slice core_clone_CloneU8 output s))
    | Safe_mode_jit_OperandSize_S32 =>
      ((s <-
          core_array_Array_index (8 :: usize) (core_ops_index_IndexSliceInst
            core_ops_range_RangeToUsize_Insts_CoreSliceIndexSliceIndexSliceSlice)
            bytes (| core_ops_range_RangeTo_end_' = (4 :: usize) |);
       alloc_vec_Vec_extend_from_slice core_clone_CloneU8 output s))
    | Safe_mode_jit_OperandSize_S64 =>
      ((let s = array_to_slice (8 :: usize) bytes in
       alloc_vec_Vec_extend_from_slice core_clone_CloneU8 output s))
    )"

(* [solana_sbpf::safe_mode::x86::{solana_sbpf::safe_mode::x86::X86Instruction}::encode]:
   Source: 'src/safe_mode/x86.rs', lines 117:4-198:5
   Visibility: public *)
definition safe_mode_x86_X86Instruction_encode
  :: "safe_mode_x86_X86Instruction_t ⇒ (u8 alloc_vec_Vec) result" where
  "safe_mode_x86_X86Instruction_encode self
    = (
    (os, b) <-
      case (Safe_mode_x86_X86Instruction_size self) of
      Safe_mode_jit_OperandSize_S0 => (Ok (Safe_mode_jit_OperandSize_S0, True))
      | Safe_mode_jit_OperandSize_S8 =>
        (Ok (Safe_mode_jit_OperandSize_S8, False))
      | Safe_mode_jit_OperandSize_S16 =>
        (Ok (Safe_mode_jit_OperandSize_S16, False))
      | Safe_mode_jit_OperandSize_S32 =>
        (Ok (Safe_mode_jit_OperandSize_S32, False))
      | Safe_mode_jit_OperandSize_S64 =>
        (Ok (Safe_mode_jit_OperandSize_S64, False));
    _ <- massert (~ b);
    b1 <-
      case os of
      Safe_mode_jit_OperandSize_S0 => (Ok False)
      | Safe_mode_jit_OperandSize_S8 => (Ok False)
      | Safe_mode_jit_OperandSize_S16 => (Ok False)
      | Safe_mode_jit_OperandSize_S32 => (Ok False)
      | Safe_mode_jit_OperandSize_S64 => (Ok True);
    let i = u8_and (Safe_mode_x86_X86Instruction_first_operand self) (8 :: u8)
    in
    let i1 =
      u8_and (Safe_mode_x86_X86Instruction_second_operand self) (8 :: u8)
    in
    let i2 = u8_and (Safe_mode_x86_X86Instruction_first_operand self) (7 :: u8)
    in
    let i3 =
      u8_and (Safe_mode_x86_X86Instruction_second_operand self) (7 :: u8)
    in
    (b2, b3, i4, i5, i6, i7, i9, displacement_size, displacement) <-
      if (Safe_mode_x86_X86Instruction_modrm self)
      then (
        (b4, i10, i11, i12, i13, i14, os1, i15) <-
          case (Safe_mode_x86_X86Instruction_indirect self) of
          None =>
            (Ok (False, 3 :: u8, i3, 0 :: u8, 0 :: u8, 0 :: u8,
              Safe_mode_jit_OperandSize_S0, 0 :: i32))
          | Some xia =>
            (case xia of
             Safe_mode_x86_X86IndirectAccess_Offset offset =>
               ((let left_val =
                   u8_and (Safe_mode_x86_X86Instruction_second_operand self)
                     (7 :: u8)
                 in
                _ <- massert (~ (left_val = (4 :: u8)));
                ri <-
                  core_ops_range_RangeInclusive_new ((-128) :: i32)
                    (127 :: i32);
                b5 <-
                  core_ops_range_RangeInclusive_contains core_cmp_PartialOrdI32
                    core_cmp_PartialOrdI32 core_cmp_PartialOrdI32 ri offset;
                (i17, os2) <-
                  if b5
                  then (Ok (1 :: u8, Safe_mode_jit_OperandSize_S8))
                  else (
                    if (offset = (0 :: i32))
                    then (
                      let i18 =
                        u8_and
                          (Safe_mode_x86_X86Instruction_second_operand self)
                          (7 :: u8)
                      in
                      if (i18 = (5 :: u8))
                      then (Ok (1 :: u8, Safe_mode_jit_OperandSize_S8))
                      else (Ok (2 :: u8, Safe_mode_jit_OperandSize_S32)))
                    else (Ok (2 :: u8, Safe_mode_jit_OperandSize_S32)));
                Ok (False, i17, i3, 0 :: u8, 0 :: u8, 0 :: u8, os2, offset)))
             | Safe_mode_x86_X86IndirectAccess_OffsetIndexShift offset index
               shift =>
               ((ri <-
                   core_ops_range_RangeInclusive_new ((-128) :: i32)
                     (127 :: i32);
                b5 <-
                  core_ops_range_RangeInclusive_contains core_cmp_PartialOrdI32
                    core_cmp_PartialOrdI32 core_cmp_PartialOrdI32 ri offset;
                (i17, displacement_size1) <-
                  if b5
                  then (Ok (1 :: u8, Safe_mode_jit_OperandSize_S8))
                  else (Ok (2 :: u8, Safe_mode_jit_OperandSize_S32));
                let index1 =
                  case
                    index
                    of
                      Safe_mode_x86_X86Register_RAX
                    =>
                    (0 :: u8)
                      |
                    Safe_mode_x86_X86Register_RCX
                    =>
                    (1 :: u8)
                      |
                    Safe_mode_x86_X86Register_RDX
                    =>
                    (2 :: u8)
                      |
                    Safe_mode_x86_X86Register_RBX
                    =>
                    (3 :: u8)
                      |
                    Safe_mode_x86_X86Register_RSP
                    =>
                    (4 :: u8)
                      |
                    Safe_mode_x86_X86Register_RBP
                    =>
                    (5 :: u8)
                      |
                    Safe_mode_x86_X86Register_RSI
                    =>
                    (6 :: u8)
                      |
                    Safe_mode_x86_X86Register_RDI
                    =>
                    (7 :: u8)
                      |
                    Safe_mode_x86_X86Register_R8
                    =>
                    (8 :: u8)
                      |
                    Safe_mode_x86_X86Register_R9
                    =>
                    (9 :: u8)
                      |
                    Safe_mode_x86_X86Register_R10
                    =>
                    (10 :: u8)
                      |
                    Safe_mode_x86_X86Register_R11
                    =>
                    (11 :: u8)
                      |
                    Safe_mode_x86_X86Register_R12
                    =>
                    (12 :: u8)
                      |
                    Safe_mode_x86_X86Register_R13
                    =>
                    (13 :: u8)
                      |
                    Safe_mode_x86_X86Register_R14
                    =>
                    (14 :: u8)
                      |
                    Safe_mode_x86_X86Register_R15
                    =>
                    (15 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM0
                    =>
                    (16 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM1
                    =>
                    (17 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM2
                    =>
                    (18 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM3
                    =>
                    (19 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM4
                    =>
                    (20 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM5
                    =>
                    (21 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM6
                    =>
                    (22 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM7
                    =>
                    (23 :: u8)
                in
                i18 <- scalar_cast U8 U8 index1;
                let i19 = u8_and i18 (8 :: u8) in
                let i20 = u8_and shift (3 :: u8) in
                let index2 =
                  case
                    index
                    of
                      Safe_mode_x86_X86Register_RAX
                    =>
                    (0 :: u8)
                      |
                    Safe_mode_x86_X86Register_RCX
                    =>
                    (1 :: u8)
                      |
                    Safe_mode_x86_X86Register_RDX
                    =>
                    (2 :: u8)
                      |
                    Safe_mode_x86_X86Register_RBX
                    =>
                    (3 :: u8)
                      |
                    Safe_mode_x86_X86Register_RSP
                    =>
                    (4 :: u8)
                      |
                    Safe_mode_x86_X86Register_RBP
                    =>
                    (5 :: u8)
                      |
                    Safe_mode_x86_X86Register_RSI
                    =>
                    (6 :: u8)
                      |
                    Safe_mode_x86_X86Register_RDI
                    =>
                    (7 :: u8)
                      |
                    Safe_mode_x86_X86Register_R8
                    =>
                    (8 :: u8)
                      |
                    Safe_mode_x86_X86Register_R9
                    =>
                    (9 :: u8)
                      |
                    Safe_mode_x86_X86Register_R10
                    =>
                    (10 :: u8)
                      |
                    Safe_mode_x86_X86Register_R11
                    =>
                    (11 :: u8)
                      |
                    Safe_mode_x86_X86Register_R12
                    =>
                    (12 :: u8)
                      |
                    Safe_mode_x86_X86Register_R13
                    =>
                    (13 :: u8)
                      |
                    Safe_mode_x86_X86Register_R14
                    =>
                    (14 :: u8)
                      |
                    Safe_mode_x86_X86Register_R15
                    =>
                    (15 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM0
                    =>
                    (16 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM1
                    =>
                    (17 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM2
                    =>
                    (18 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM3
                    =>
                    (19 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM4
                    =>
                    (20 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM5
                    =>
                    (21 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM6
                    =>
                    (22 :: u8)
                      |
                    Safe_mode_x86_X86Register_MM7
                    =>
                    (23 :: u8)
                in
                i21 <- scalar_cast U8 U8 index2;
                let i22 = u8_and i21 (7 :: u8) in
                let i23 =
                  u8_and (Safe_mode_x86_X86Instruction_second_operand self)
                    (7 :: u8)
                in
                Ok (i19 ≠ (0 :: u8), i17, 4 :: u8, i20, i22, i23,
                  displacement_size1, offset))));
        Ok (True, b4, i10, i11, i12, i13, i14, os1, i15))
      else (
        Ok (False, False, 0 :: u8, i3, 0 :: u8, 0 :: u8, 0 :: u8,
          Safe_mode_jit_OperandSize_S0, 0 :: i32));
    b4 <-
      case os of
      Safe_mode_jit_OperandSize_S0 => (Ok False)
      | Safe_mode_jit_OperandSize_S8 => (Ok False)
      | Safe_mode_jit_OperandSize_S16 => (Ok True)
      | Safe_mode_jit_OperandSize_S32 => (Ok False)
      | Safe_mode_jit_OperandSize_S64 => (Ok False);
    output <-
      if b4
      then (alloc_vec_Vec_push (alloc_vec_Vec_new) (102 :: u8))
      else (Ok (alloc_vec_Vec_new));
    i10 <- scalar_cast_bool U8 b1;
    i11 <- u8_shl i10 (3 :: i32);
    i12 <- scalar_cast_bool U8 (i ≠ (0 :: u8));
    i13 <- u8_shl i12 (2 :: i32);
    let i14 = u8_or i11 i13 in
    i15 <- scalar_cast_bool U8 b3;
    i17 <- u8_shl i15 (1 :: i32);
    let i18 = u8_or i14 i17 in
    i19 <- scalar_cast_bool U8 (i1 ≠ (0 :: u8));
    let rex_byte = u8_or i18 i19 in
    output1 <-
      if (rex_byte ≠ (0 :: u8))
      then (
        let i20 = u8_or (64 :: u8) rex_byte in alloc_vec_Vec_push output i20)
      else (Ok output);
    output2 <-
      case (Safe_mode_x86_X86Instruction_opcode_escape_sequence self) of
      1 :: u8 => (alloc_vec_Vec_push output1 (15 :: u8))
      | 2 :: u8 =>
        ((let a = core_num_U16_to_le_bytes (3896 :: u16) in
         let s = array_to_slice (2 :: usize) a in
         alloc_vec_Vec_extend_from_slice core_clone_CloneU8 output1 s))
      | 3 :: u8 =>
        ((let a = core_num_U16_to_le_bytes (3898 :: u16) in
         let s = array_to_slice (2 :: usize) a in
         alloc_vec_Vec_extend_from_slice core_clone_CloneU8 output1 s))
      | _ => (Ok output1);
    output3 <-
      alloc_vec_Vec_push output2 (Safe_mode_x86_X86Instruction_opcode self);
    output4 <-
      if b2
      then (
        i20 <- u8_shl i4 (6 :: i32);
        i21 <- u8_shl i2 (3 :: i32);
        let i22 = u8_or i20 i21 in
        let i23 = u8_or i22 i5 in
        output5 <- alloc_vec_Vec_push output3 i23;
        i24 <- u8_shl i6 (6 :: i32);
        i25 <- u8_shl i7 (3 :: i32);
        let i26 = u8_or i24 i25 in
        let sib_byte = u8_or i26 i9 in
        output6 <-
          if (sib_byte ≠ (0 :: u8))
          then (alloc_vec_Vec_push output5 sib_byte)
          else (Ok output5);
        i27 <- scalar_cast I32 U64 displacement;
        safe_mode_x86_emit_variable_length output6 displacement_size i27)
      else (Ok output3);
    i20 <- scalar_cast I64 U64 (Safe_mode_x86_X86Instruction_immediate self);
    safe_mode_x86_emit_variable_length output4
      (Safe_mode_x86_X86Instruction_immediate_size self) i20
    )"

end
